#!/bin/bash

echo "Para configurar el webhook de Slack:"
echo ""
echo "1. Ve a https://api.slack.com/apps"
echo "2. Selecciona tu aplicación 'Claude MCP Feedback'"
echo "3. En el menú lateral, ve a 'Event Subscriptions'"
echo "4. Activa 'Enable Events'"
echo "5. En 'Request URL', ingresa:"
echo "   https://claude-mcp-slack-feedback-7af7we7bvq-ew.a.run.app/slack/events"
echo ""
echo "6. Espera a que Slack verifique la URL (debería mostrar 'Verified')"
echo ""
echo "7. En 'Subscribe to bot events', añade estos eventos:"
echo "   - message.channels"
echo "   - message.groups"
echo "   - message.im"
echo "   - message.mpim"
echo ""
echo "8. Guarda los cambios"
echo ""
echo "Una vez configurado, Slack enviará las respuestas a la Cloud Function"
echo "y el MCP local las obtendrá mediante polling."